### ISSUE TITLE
Missing items in crafting list

### ISSUE THREAD

**Issue by Taelia** [Tickthokk/ffxivcrafting#267]
http://ffxivcrafting.com/crafting/list?BSM:21:25:1:0

When I go to the above page, I'm missing all kinds of recipes. The Initiate's Awl doesn't appear, the Iron Sledgehammer, Iron Culinary Knife, etc.  while they are definitely BSM recipes between level 21 and 25.

**Comment by medouneu** [comment]
http://ffxivcrafting.com/crafting/list?BSM:16:20:1:0

Same issue occurs for three BSM recipes between 16 and 20: Iron Awl, Initiate's Sledgehammer, and Iron Claw Hammer. However, if I choose to include Dyes & Furniture, they do appear in the list.

**Comment by Tickthokk** [comment]
This was an issue with all offhand/secondary tools.  It'll be fixed in the next update.  Thanks!
