### ISSUE TITLE
Unable to access any recipies and levequests after the latest update

### ISSUE THREAD

**Issue by t999uk** [Tickthokk/ffxivcrafting#275]
when I click on the crafting book, levequest all that come up is a massages asying " sorrthing somethings gone wrong"
![error](https://cloud.githubusercontent.com/assets/2357332/7272851/00a67236-e8e6-11e4-8fea-cc5b146f636d.png)

**Comment by t999uk** [comment]
seems to be working again now

**Comment by Tickthokk** [comment]
Yeah, the MySQL client went down.   Thanks for the report!
